### PR TITLE
Fix tracking

### PR DESCRIPTION
**Pull request by caufieldjh**
Addressing #28 and #31 - tracking file and lock file are each now accessed only from remote copy.

### CODE REVIEW

**Comment by justaddcoffee** [comment]
@caufieldjh does it make sense to make `--bucket` a required Click argument?

**Comment by caufieldjh** [comment]
Probably not at the moment. I was envisioning a use case in which we or others could upload to multiple buckets for the sake of redundancy.

**Comment by justaddcoffee** [comment]
> Probably not at the moment. I was envisioning a use case in which we or others could upload to multiple buckets for the sake of redundancy.

I can see that designating multiple buckets would be useful, but what's the use case for not specifying a bucket? We'll always need a `tracking.yaml` right? 

I guess it might be useful to do a dry run with no bucket specified, to see if the whole transform works?

**Comment by caufieldjh** [comment]
Oops, I just misunderstood what you said - I interpreted that as suggesting to remove the argument entirely, but I see you meant to make it required, which makes more sense. Made a commit for it.

**Comment by justaddcoffee** [comment]
I think [this](https://github.com/Knowledge-Graph-Hub/kg-obo/blob/7490b8f7015b5ac24ad541295eb680c0956b14bb/tests/test_transform.py#L193) path is wrong (my fault)

**Pull request merged**
