### PR TITLE
Add option to overwrite existing transform files on KG-OBO

### PR DESCRIPTION
**Pull request by caufieldjh**

### CODE REVIEW

**Comment by justaddcoffee** [comment]
Is this not harmful? In theory, this will allow the code to overwrite any file in KG-Hub, so a given URL is not guaranteed to contain the same content from one day to the next

**Comment by caufieldjh** [comment]
True! This is here so I can replace all the most recent transforms with their node-normalized versions, and that shouldn't need to happen under usual conditions.

**Comment by justaddcoffee** [comment]
Ah okay. What I've done in the past is to manually fix any files that have been uploaded to S3 that need to changed - if that's not possible, it may be a good idea to at least create a flag (`--force` or something like that) that permits overwriting files and is off by default

Thoughts?

**Comment by caufieldjh** [comment]
> ...create a flag (--force or something like that) that permits overwriting files...
You read my mind! That will go in this PR.

**Comment by justaddcoffee** [comment]
+1

**Comment by justaddcoffee** [comment]
Adding: this overwriting still seems a bit dangerous to me, but if it's off by default I guess that limits the danger a bit

**Comment by caufieldjh** [comment]
I'll agree that it does feel icky. I should probably include a failsafe to restrict this to the most recent KG-OBO transform, so the archival versions are retained

**Comment by caufieldjh** [comment]
> I should probably include a failsafe

Looks like I already included this 
https://github.com/Knowledge-Graph-Hub/kg-obo/blob/3b0cc821044cd135532e62355b770fd6c310744b/kg_obo/transform.py#L906-L918

**Pull request merged**
